### ISSUE TITLE
How to calculate avg value of the metrics

### ISSUE THREAD

**Issue by animesh-007** [vigsivan/RWCNet#4]
I have tried to follow the readme available at `train_oasis` and ran the `eval.py`. But it doesn't give the avg values of the metrics scores. @vigsivan, Can you let me know how you calculate the avg values of the metric scores as you have reported in the readme? 

I have tried to use L2R official repo too as mentioned in #2 but I am getting avg value of `0.72`.

**Comment by vigsivan** [comment]
Hi aimesh,
Here's a quick script to get the average:

```python
import json
import numpy as np
with open("metrics.json", 'r') as f:
    metrics = json.load(f)

dice_scores = [1-v["metrics"]["dice"] for v in  metrics.values()]
print(np.mean(dice_scores)) # 0.8048

```
I'll modify the evaluation script to produce an average  probably later this week. Closing, but feel free to follow up.

**Comment by vigsivan** [comment]
Re-opening, so that I actually remember to get to this :)

**Comment by animesh-007** [comment]
> Re-opening, so that I actually remember to get to this :)

Will it be helpful to you if I raise a PR implementing this?😇

**Comment by vigsivan** [comment]
Thanks for offering, but I'll address it.

**Comment by vigsivan** [comment]
Closing, as I think I prefer having a separate script to analyze the results.
